apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cp
  template:
    metadata:
      labels:
        app: cp
    spec:
      containers:
      - name: cp
        image: us-central1-docker.pkg.dev/practical-case-392912/monitor-cp/cp:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
            ephemeral-storage: "200Mi"
          limits:
            memory: "100Mi"
            cpu: "50m"
            ephemeral-storage: "200Mi"
---



